# Generated by Django 5.2.8 on 2025-11-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('CollegeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SampleWorks.college')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.IntegerField(primary_key=True, serialize=False)),
                ('years_in', models.FloatField()),
                ('dob', models.DateField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampleWorks.college')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('last_clocked_in', models.DateTimeField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampleWorks.college')),
                ('student', models.ManyToManyField(to='SampleWorks.student')),
            ],
        ),
    ]
